### ISSUE TITLE
Add isPresent to neetoUtils

### ISSUE THREAD

**Issue by divyajomi08** [bigbinary/neeto-utils#24]
Add isPresent to neetoUtils
@yedhink

**Comment by yedhink** [comment]
@edwinbbu _a

Can you please take this up or assign to right person?

Refer: https://github.com/bigbinary/neeto-desk-web/blob/d7fd7956a41d44b73c17055dac74faabaf944d3f/app/javascript/Admin/Components/common.js#L158-L160

**Comment by edwinbbu** [comment]
Let's ignore `isPresent`. It internally uses `ramdba`. Let's not add packages and create wrappers.
